create schema scoreDB;
use scoreDB;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- Tabela de Usuários
CREATE TABLE usuario (
  id int(11) NOT NULL AUTO_INCREMENT,
  NOME varchar(255) DEFAULT NULL,
  IDADE int(11) DEFAULT NULL,
  SEXO varchar(10) DEFAULT NULL,
  LOGIN varchar(64) DEFAULT NULL,
  SENHA varchar(64) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (LOGIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE usuario
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

-- Tabela de Scores
CREATE TABLE score (
  id int(11) NOT NULL,
  USUARIO_ID int(11) NOT NULL,
  JOGO varchar(64) NOT NULL,
  PONTOS int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (USUARIO_ID) REFERENCES usuario (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE score
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;
 
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
